import 'package:flutter/material.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text(
          "Terms & Conditions",
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: EdgeInsetsGeometry.all(16.0),
        child: Column(
          children: [
            Text(
                "Welcome to THIRD EYE, an emotional wellness mobile application developed by DS Developers under the guidance of Dr. Himanshu Rathwa. By downloading or using this application, you agree to the terms and conditions outlined below. THIRD EYE is designed as a tool for self-awareness and personal reflection. It does not provide medical, psychiatric, or therapeutic advice, and any insights generated by the app are intended solely for personal reflection — not as a substitute for professional consultation."),
            SizedBox(
              height: 20,
            ),
            Align(
              alignment: Alignment.centerLeft,
              child: Text(
                "Closure 2",
                style: TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
            Text(
                "Users are encouraged to provide honest responses to the daily self-assessment questions to ensure accurate insights and meaningful emotional progress tracking. All collected data is securely stored using Google Firebase, ensuring privacy and protection at every stage. The intellectual property, design, content, and algorithms of THIRD EYE are exclusively owned by DS Developers and Dr. Himanshu Rathwa, and users are not permitted to reproduce, modify, or distribute any part of the app without prior written consent. Once the interface and theme are finalized, only agreed-upon bug fixes or scope-based updates will be implemented. Certificates of Self-Awareness are awarded to users who maintain a consistent 21-day participation streak."),
            SizedBox(
              height: 20,
            ),
            Text(
                "THIRD EYE may occasionally undergo maintenance or updates, during which brief service interruptions may occur. The developers are not responsible for any emotional outcomes, interpretations, or decisions made based on the app’s insights. These Terms and Conditions may be updated periodically to reflect improvements or policy changes. By continuing to use the application, users acknowledge and accept the latest version of these terms. For inquiries or support, please contact thirdeye.support@gmail.com. © 2025 THIRD EYE. All Rights Reserved."),
          ],
        ),
      ),
    );
  }
}

