// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8z2gVZz5qnsfWjmcACw9C7uc2KQwwGs',
    appId: '1:764937457152:web:99225786732a4d084e92e5',
    messagingSenderId: '764937457152',
    projectId: 'thirdeye-emotion-tracker',
    authDomain: 'thirdeye-emotion-tracker.firebaseapp.com',
    storageBucket: 'thirdeye-emotion-tracker.firebasestorage.app',
    measurementId: 'G-BWDNK76V6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGovxbmpHue5CY66cPdadDIvH9R_Ccauo',
    appId: '1:764937457152:android:3dfa07d693cc903e4e92e5',
    messagingSenderId: '764937457152',
    projectId: 'thirdeye-emotion-tracker',
    storageBucket: 'thirdeye-emotion-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF28NCxzBAPfMPenepiyUH7-7RIm1tqXU',
    appId: '1:764937457152:ios:96755010717b303a4e92e5',
    messagingSenderId: '764937457152',
    projectId: 'thirdeye-emotion-tracker',
    storageBucket: 'thirdeye-emotion-tracker.firebasestorage.app',
    androidClientId: '764937457152-sgfnnuo4tna6nsp7r66cdknet7hvrltv.apps.googleusercontent.com',
    iosClientId: '764937457152-7okch3m67sj7n0un5aafp4k9pce4uaou.apps.googleusercontent.com',
    iosBundleId: 'com.emotiontracker.thirdeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF28NCxzBAPfMPenepiyUH7-7RIm1tqXU',
    appId: '1:764937457152:ios:8112d604d429837f4e92e5',
    messagingSenderId: '764937457152',
    projectId: 'thirdeye-emotion-tracker',
    storageBucket: 'thirdeye-emotion-tracker.firebasestorage.app',
    androidClientId: '764937457152-sgfnnuo4tna6nsp7r66cdknet7hvrltv.apps.googleusercontent.com',
    iosClientId: '764937457152-e89iruesk3pim2e4k0i9vp95nkc1drq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdeye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj8z2gVZz5qnsfWjmcACw9C7uc2KQwwGs',
    appId: '1:764937457152:web:c7abe259dc2a657e4e92e5',
    messagingSenderId: '764937457152',
    projectId: 'thirdeye-emotion-tracker',
    authDomain: 'thirdeye-emotion-tracker.firebaseapp.com',
    storageBucket: 'thirdeye-emotion-tracker.firebasestorage.app',
    measurementId: 'G-01HS19RPMB',
  );
}
