// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6tuhBPTMG3FmpO_Tl_1qeakmqQUcJF6I',
    appId: '1:831786695055:web:088e7a123ca6954d8a33fa',
    messagingSenderId: '831786695055',
    projectId: 'fir-demo-a6516',
    authDomain: 'fir-demo-a6516.firebaseapp.com',
    storageBucket: 'fir-demo-a6516.firebasestorage.app',
    measurementId: 'G-4YKNX5E9NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb4aF_XVjeIDh4R-4AIAaCwsAvZ1AbiHg',
    appId: '1:831786695055:android:23409509552f005b8a33fa',
    messagingSenderId: '831786695055',
    projectId: 'fir-demo-a6516',
    storageBucket: 'fir-demo-a6516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbvHDkRCibLF_Cy276p1JZyYuni9bd-5o',
    appId: '1:831786695055:ios:c061c7d2cd6c543d8a33fa',
    messagingSenderId: '831786695055',
    projectId: 'fir-demo-a6516',
    storageBucket: 'fir-demo-a6516.firebasestorage.app',
    iosBundleId: 'com.example.thirdeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbvHDkRCibLF_Cy276p1JZyYuni9bd-5o',
    appId: '1:831786695055:ios:c061c7d2cd6c543d8a33fa',
    messagingSenderId: '831786695055',
    projectId: 'fir-demo-a6516',
    storageBucket: 'fir-demo-a6516.firebasestorage.app',
    iosBundleId: 'com.example.thirdeye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6tuhBPTMG3FmpO_Tl_1qeakmqQUcJF6I',
    appId: '1:831786695055:web:f7301a2428df313c8a33fa',
    messagingSenderId: '831786695055',
    projectId: 'fir-demo-a6516',
    authDomain: 'fir-demo-a6516.firebaseapp.com',
    storageBucket: 'fir-demo-a6516.firebasestorage.app',
    measurementId: 'G-4F63V0RLKW',
  );
}
